---
kind: pipeline
name: build-rvloader
type: kubernetes

steps:
- name: build
  image: lib42/devkitpro:rvloader
  commands:
    - make
    - mkdir -p /release/apps/rvloader /release/channels /release/games /release/rvloader/themes /release/vc /release/wbfs
    - cp boot.dol /release/apps/rvloader/
    - cp -r theme /release/rvloader/themes/main
  volumes:
  - name: cache
    path: /release

- name: package
  image: lib42/devkitpro:rvloader
  commands:
    - tar -czf rvloader-${DRONE_TAG}.tar.gz /release/
    - mv rvloader-*.tar.gz /release/
    - ls -l /release
  volumes:
  - name: cache
    path: /release
  when:
    event: tag

- name: publish
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    files:
    - /release/rvloader-*.tar.gz
  volumes:
  - name: cache
    path: /release
  when:
    event: tag

volumes:
- name: cache
  temp: {}
